---
title: "Limits of the First Amendment"
description: |
  This research paper explores the limits of the First Amendment in the era of social networks and private ownership.
author:
  - name: Grace Christensen 
    url: https://example.com/norajones
    affiliation: The George Washington University
    affiliation_url: https://example.com/spacelysprokets
date: December 12, 2019
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

In the age of social media, where most, if not all, daily communication is done online, certain actors have more control over speech than others.  Social networks have become the first place that United States citizens take their complaints against the government, and yet the government itself has no control over these platforms.  In a world where Twitter videos of police brutality are inspiring change and petitions are shared across Facebook, how do we protect the freedom of speech when the government has no control over these private entities?  Since the First Amendment is only applicable to state actors, the freedom of speech is under attack from these third party companies.  With social media changing how U.S. citizens communicate daily, is the First Amendment broad enough to protect the freedom of expression to the extent necessary for our political participation?

Understanding the current state of Internet protections is the first step in answering this question, the first of which can be seen in 1997 as decided by the Supreme Court.  When Congress passed the Communications Decency Act of 1996 (CDA) in an attempt to protect minors from being exposed to obscene or indecent content through the Internet, the American Civil Liberties Union (ACLU) felt that this act was an unconstitutional violation of the U.S. Constitution’s First and Fifth Amendments, as the CDA was a content-based regulation that was both too broad and too vague.  In Reno v. American Civil Liberties Union (1997), the Supreme Court asked whether or not this act was a violation of the First Amendment through its vague and broad restriction to the Internet.  The Court ultimately ruled in favor of the ACLU, determining that the CDA’s provisions which regulate the “knowing transmission” of indecent or offensive communication were in direct violation of the U.S. First Amendment.  In doing so, however, the Court also came together in support of the Internet as a means for public discourse.  In the majority opinion, Justice John Paul Stevens acknowledged that “the Internet… provides relatively unlimited low-cost capacity for communication of all kinds,” and “any person… can become a town cried with a voice that resonates farther than it could from any soapbox.  Through the use of Web pages, mail exploders, and newsgroups, the same individual can become a pamphleteer.”  While blocking a ban on the Internet, the Supreme Court also recognized the power and the importance of the Internet for our political participation.

However, this was not the only instance in which the Supreme Court has acknowledged the importance of the Internet as a means for public discourse.  Two decades later, when North Carolina resident Lester Gerard Packingham was arrested for using Facebook in direct opposition of North Carolina Gen. Stat. § 14-202.5, which prohibited registered sex offenders from using commercial social networking websites where minors were also able to become members or to create personal web pages, the argument made its way up to the Supreme Court.  Packingham v. North Carolina (2017) asked the Court whether or not North Carolina’s statute, which barred all usage of networking sites where minors could create accounts, regardless of any interactions with them, was a violation of the U.S. First Amendment.  The Supreme Court ultimately ruled in favor of Packingham, and in doing so, the Court once again accredited the Internet as a vital aspect of American democracy.  The Court ruled that the First Amendment provides all persons access to places where they can speak and listen and that today, “the most important places (in a spatial sense) for the exchange of views… is cyberspace.”  The Court found that websites “provide perhaps the most powerful mechanisms available to a private citizen to make his or her voice heard,” and “to foreclose access to social media altogether is to prevent the user from engaging in the legitimate exercise of First Amendment rights.”  While the Court exercised caution in defining the relationship between the First Amendment and the protection it provides for access to social networks, Packingham v. North Carolina still highlights the importance of access to the Internet in exercising First Amendment rights.

However, it is not just the Supreme Court that recognizes the power that social networks afford to the public.  In 2012, Jarret Eaglin was convicted for failing to register as a sex offender.  As punishment, Eaglin was sentenced to one year in jail, followed by eleven years of supervised release.  As part of his supervised release, Eaglin was not only banned from accessing the Internet without prior specific permission of the court, but he was also forbidden from viewing or possessing adult pornography.  In 2017, the U.S. District Court for the Northern District of New York found that Eaglin had violated these conditions.  Eaglin challenged this decision and appealed his case to the United States Court of Appeals for the Second Circuit, asking if an untailored eleven-year ban on the Internet was fair punishment when the charge is unrelated to the crime.  Ultimately the case was remanded, meaning that it was returned to the lower court for reconsideration.  Additionally, the court announced that “to consign an individual to a life virtually without access to the Internet is to exile that individual from society.”  The court also found that to deny one access to the Internet not only is a severe encroachment of First Amendment rights, but it is also a deprivation of “the opportunity to engage with modern society.”  Social networks and the Internet, the court found, are essential elements of life in the modern world.

While the Supreme Court has expressed the importance of social networks and the Internet for public and political discourse, a barrier still exists between these platforms and First Amendment protections.  Because these social networks are owned and operated by private entities, the government has no legitimate interest to intervene in the behaviors of these networks unless they had previously entered into a close agreement with said private company, as shown by Nyabaw v. Facebook (2018).  In 2016, when Facebook locked Collins O. Nyabwa’s account for “security reasons,” Nyabwa attempted to sue over violation of his First Amendment rights.  The court was asked to determine if Facebook violated said rights by entering into an agreement with the government prior to the locking of Nyabwa’s account.  When Nyabwa failed to produce evidence of this relationship, the court dismissed his case for failure to state a claim for relief and/or frivolous pursuit.  Since Facebook is a private corporation and Nyabwa was unable to produce documentation showing that the company entered into an agreement with the state to deny citizens their constitutionally-granted rights, Nyabwa’s suit was dismissed.  Despite the value that social networks have within American democracy, private companies are still unable to be sued in violation of First Amendment rights unless there is a close connection between the state and the company.

When it comes to public officials, however, the state is awarded a small amount of room to intervene.  Donald Trump and his use of Twitter are a perfect example of this.  Since Donald Trump’s Twitter account (@realDonaldTrump) has been used throughout his presidency to share policy announcements and engage with constitutes, Twitter users that have been blocked have complained saying that their First Amendment rights have been violated.  The Knight First Amendment Institute at Columbia University sued President Trump as well as other White House officials on these users’ behalf, leaving the court to question whether President Donald Trump’s usage of the block function on his personal Twitter account violates citizens’ First Amendment rights.  The court held in favor of the Knight First Amendment Institute, stating that President Trump’s blocking of these users is unconstitutional as it limits users’ access to a platform he uses in such an official capacity.  In addition, the court determined that President Trump’s Twitter is a public forum due to how he has chosen to use the platform, and as such, his public account is not allowed to block users where he is operating in an official capacity.  However, the court did not comment as to whether this decision would stand if the account in question were private, nor did they comment on whether or not the First Amendment binds private social network companies.  The court did, however, acknowledge Twitter as a space where public forums can be built, which ultimately reaffirms the value of social media within our democracy.

Understanding the pressure that is placed on them in regards to free speech, these private companies have begun to make internal changes.  Facebook specifically has just announced its own version of the Supreme Court, according to The Atlantic.  The company will now be using a 40-member board that will make decisions regarding posts that Facebook has removed through its monitoring software.  Facebook will begin the member selection process, but thereafter will rely on the board itself to select members, each who will serve a three-year term.  However, it is not the First Amendment that these board members will be relying on, but rather, they will merely be interpreting the platform’s existing policies.  Platforms can remove lawful but hateful, harassing, or misleading and offensive posts, ultimately restricting speech much more than they are protecting it.  In a recent speech given by Facebook CEO Mark Zuckerberg following the release of leaked audio by The Verge, Zuckerberg talked about the importance of free speech, giving people a voice, and how it brings people together, according to Vox.  Zuckerberg said that “More people being able to share their experiences and perspectives has always been necessary to build a more inclusive society,” and yet he stands by their decision to establish an independent oversight board.  Zuckerberg made a big show of being transparent through these decisions, but ultimately said nothing of value, once again leaving an air of uncertainty around Facebook and their attitudes towards the First Amendment.

In light of this all, it is essential to reevaluate the First Amendment as it relates to social networks and the Internet.  Since the twenty-first century has people communicating more online than they are in traditional public forums such as on the streets and in parks, it is important that the First Amendment expands to protect these new forums.  Instead of requiring state action, the U.S. Supreme Court should interpret the First Amendment in a new way that would limit openly oppressive and unfair censorship by powerful private entities.  While this change would likely receive substantial pushback, the power of social networks and the Internet within American society is only going to grow from here, so it is important to limit their power before it is too late.

Given the recognition that the Supreme Court has given to the power of social networks and the Internet in the last two decades, it is likely that this change is already on its way.  With these platforms only growing in value within society, it is unlikely that they will be allowed to continue to grow with limited restraints.  While extending the First Amendment to social networks and the Internet is the most effective way to do this, it is entirely possible that other avenues may form to limit the powers of these private companies.  Regardless of the route taken, though, it is incredibly unlikely that these private entities are allowed to continue to grow without any form of restraint.  While these actions are likely to be met with resistance from corporate America, the benefits they will have for everyday citizens will far outweigh these.

With social media changing how U.S. citizens communicate daily, the First Amendment needs to be expanded to protect the freedom of expression for political participation to continue.  With the Supreme Court recognizing the power and importance of the Internet and social networks in the last two decades, it only makes sense that the First Amendment be broadened to protect speech on these platforms.
